Roguelike3
tiginamaria/Roguelike pull request #9
Opened 2020-04-28 22:56 UTC by tiginamaria

2020-05-10 18:10 UTC, yurii-litvinov requested changes

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Initialization/FileLevelFactory.cs
> +        ///     Creates the factory by the path to a file with a level description.
Не, обычно отступ тут не ставится

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Initialization/FileLevelFactory.cs
> +            }
Лучше это всё было писать на .NET Core, с C# 8 (под .NET Framework без специальных ухищрений доступен только C# 7.3), и вообще, .NET Framework нынче следует использовать, только если на это есть веская причина (например, использование WPF). С выходом .NET 5 .NET Framework станет уж совсем legacy-технологией.

Так вот, почему C# 8: с switch expression (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression) это можно было бы вдвое короче записать.

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Initialization/FileLevelFactory.cs
> +        }
Между методами ставится пустая строка по стайлгайду

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Initialization/FileLevelFactory.cs
> +        }
И методы-однострочники лучше писать через `=>`, это и в C# 7.3 было:
```csharp
private static Position GetPosition(ref int index, string[] info)
            => new Position(int.Parse(info[index++]), int.Parse(info[index++]));
```

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Initialization/ILevelFactory.cs
> +    public abstract class ILevelFactory
Раз это теперь абстрактный класс, надо убрать префикс I, в дотнете I --- Interface по стайлгайду

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Input/Controllers/IUpdatable.cs
> +        void Update();
Методам интерфейса тоже неплохо бы комментарии

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Input/InputLoop.cs
> +
Лишняя пустая строчка :)

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Input/Processors/InventoryProcessor.cs
> +    public class InventoryProcessor: IInputProcessor
А тут вообще комментария не хватает

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/Inventory/InventoryFactory.cs
> +    public class InventoryFactory
По стайлгайду положено "один класс --- один файл"

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/Mobs/MobFactory.cs
> +    public class MobType
Тогда и сам класс можно сделать static

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/Objects/BoardObject.cs
> +    public class BoardObject
Тоже, static.

2020-05-10 18:10 UTC, yurii-litvinov commented on RoguelikeTest/ConfusionTests.cs
> +        public void MobConfusePlayerDyeTest()
Dye, опечатка, видимо

2020-05-10 18:10 UTC, yurii-litvinov commented on RoguelikeTest/InventoryTest.cs
> +
Ммм

2020-05-10 18:10 UTC, yurii-litvinov commented on RoguelikeTest/LevelConfigurationTests.cs
> + namespace TestRoguelike
Пробел лишний добавился

2020-05-10 18:10 UTC, yurii-litvinov commented on RoguelikeTest/PlayerInteractionTests.cs
> +   using System.IO;
Что-то с отступами не то

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/PlayerModel/Player.cs
> +            statistics.Health = Math.Max(0, statistics.Health - other.GetStatistics().Force / 2);
Интересно, что у вас вся боевая система спрятана в AcceptConfuse. Как будто бы конфузия --- это ключевое свойство боя, вокруг которого всё строится :) Я бы хотя бы переименовал этот метод (AcceptDamage?), а лучше бы вообще вынес код боёвки в отдельный класс. В конце концов, в бою участвует два персонажа, лучше бы, чтобы ресолв боя проходил не в одном из них, а где-то вовне.

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/Inventory/IncreaseHealthItem.cs
> +    public class IncreaseHealthItem : InventoryItem
Не уверен, что этим штукам нужны свои отдельные классы. У них ведь нет никакого поведения, можно было бы хранить их данные в классе Item и всё.

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/PlayerModel/Player.cs
> +            }
Мм, при снятии вещи она исчезает навсегда. Не знаю, задумывалось ли так, но fells like bug.

2020-05-10 18:10 UTC, yurii-litvinov commented on Roguelike/Model/LevelSnapshot.cs
> +        }
Можно было бы сюда же логику загрузки уровня вынести. По крайней мере, в части парсинга входного файла. Это было бы более в духе паттерна "Хранитель" и улучшило бы инкапсуляцию.

2020-05-10 18:15 UTC, yurii-litvinov commented
Общие комментарии по задачам.

Первая часть: теперь почти всё хорошо, надо только существенно больше комментариев и сделать код более идиоматичным для C#. Не настаиваю на переходе на .NET Core, но рекомендую.

Вторая часть: надо что-то сделать с боёвкой, сейчас она архитектурно проигнорирована, скажем так. И тоже надо комментарии и навести стайлгайд (я в коде откомментил по одному разу на каждую проблему, но их там по несколько экземпляров одного типа проблем).

Третья часть: попробовать загрузку из файла перенести в LevelSnapshot, если получится хуже (что вполне возможно), оставить как было, но откомментить. И с уничтожением предмета при снятии --- тоже, либо поправьте, либо объясните необычное геймдизайнерское решение. И тут ещё совсем беда с юнит-тестами, а они нужны.

2020-06-03 20:06 UTC, vvselischev commented
Третья часть: при реализации сети оказалось удобным переиспользовать snapshot для посылки начального игрового состояния, а логику создания уровня оставить полноценной фабрикой, т.к. её тоже нужно дополнительно конфигурировать в зависимости от режима игры. То есть с одной стороны, логика создания уровня достаточно сложная, чтобы ей нагружать этот класс, а с другой, этот класс удобен именно как представляющий состояние игры для его передачи.

2020-06-11 22:00 UTC, zuevmaxim commented on Roguelike/Model/PlayerModel/Player.cs
> +            }
Так и задумывалось. Мы предполагали, что предметы одноразовые - если ты его использовал, то никто больше не может.

2020-06-11 22:04 UTC, zuevmaxim commented on Roguelike/Model/Inventory/IncreaseHealthItem.cs
> +    public class IncreaseHealthItem : InventoryItem
Мы решили дать им названия. И так удобнее для парсинга.

2021-04-25 21:06 UTC, merged